var x = Math.ceil(10.380)
document.write(x)
document.write("<br>")
var x = Math.floor(10.380)
document.write(x)
document.write("<br>")
var x = Math.round(10.380)
document.write(x)
document.write("<br>")
var x = Math.random()
document.write(x)
document.write("<br>")