var nome = 'Arthur Resende'
document.write(nome.length)
document.write("<br>")
document.write(nome[0])
document.write("<br>")
document.write(nome.charAt(1))
document.write("<br>")
document.write(nome.indexOf('t'))
document.write("<br>")
document.write(nome.replace('Resende', 'Gomes'))
document.write("<br>")
document.write(nome.toUpperCase())
document.write("<br>")
document.write(nome.toLowerCase())
document.write("<br>")
document.write('-- '+ nome.trim() +' --')