var d = new Date()
document.write(d)
document.write("<br>")
document.write("Dia: " + d.getDate())
document.write("<br>")
d_month= parseInt(d.getMonth()) + 1
document.write("Mês: " + d_month )
document.write("<br>")
document.write("Ano: " + d.getFullYear())
document.write("<br>")
document.write("Hora: " + d.getHours())
document.write("<br>")
document.write("Minuto: " + d.getMinutes())
document.write("<br>")
document.write("Segundos: " + d.getSeconds())
document.write("<br>")